name: k-seq
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cycler=0.10.0
  - freetype=2.10.4
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.3.0
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.3
  - pillow=8.0.1
  - pip=20.2.4
  - pyparsing=2.4.7
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.51.0
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - doc-helper==1.1.1
    - python-levenshtein==0.12.0
    - seq-landscape==0.1.0b1
    - yutility==0.6.3
