name: k-seq
channels:
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython=7.19.0
  - jupyter=1.0.0
  - matplotlib=3.3.2
  - notebook=6.1.4
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3
  - python=3.8.5
  - scipy=1.5.2
  - seaborn=0.11.0
  - tqdm=4.51.0
  - pip:
    - doc-helper==1.1.1
    - python-levenshtein==0.12.0
    - seq-landscape==0.1.0b1
    - yutility==0.6.3
